grafana:
  enabled: true
  sidecar:
    dashboards:
      enabled: true
  dashboardsConfigMaps:
    istiografanadashboards: "istio-grafana-dashboards"
    istioservicesgrafanadashboards: "istio-services-grafana-dashboards"
  additionalDataSources:
    - name: "Loki"
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100
      access: proxy
      jsonData:
        maxLines: 1000
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: "loki"
      static_configs:
        - targets: ["loki.monitoring.svc.cluster.local:3100"]