apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.authNamespace }}
  labels:
    app: my-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-auth-deployment
  namespace: {{ .Values.authNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-auth
  template:
    metadata:
      labels:
        app: svc-auth
    spec:
      containers:
      - name: svc-auth
        image: svc-auth:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-auth
  namespace: {{ .Values.authNamespace }}
spec:
  selector:
    app: svc-auth
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
